Review README
openstack-charmers/charm-ceph-iscsi pull request #16
Opened 2020-07-03 22:07 UTC by pmatulis

There is no bug tracker set up in Launchpad so I have included the standard Bugs section but left it commented out.

2020-07-06 15:23 UTC, pmatulis commented
The VMWare integration section will likely be moved to the dedicated Ceph docs once they exist.

2020-07-07 13:00 UTC, gnuoy requested changes
One small nit

2020-07-07 13:00 UTC, gnuoy commented on README.md
> +    juju deploy -n 2 cs:~gnuoy/ceph-iscsi-08
Can we change this to cs:~openstack-charmers-next/ceph-iscsi ?

2020-07-07 14:42 UTC, pmatulis commented on README.md
> +    juju deploy -n 2 cs:~gnuoy/ceph-iscsi-08
Yep,

2020-07-07 14:57 UTC, gnuoy approved these changes
Thanks for the updates

2020-07-07 14:57 UTC, merged